<form id="article_form" method="post">
    <label for="title">Titre :</label>
        <input id="title" name="title" type="text" placeholder="Titre de l'article" required="required">
    <br>
    <label for="content">Contenu :</label>
        <textarea id="content" name="content" placeholder="Contenu de l'article" required="required"></textarea>
    <br>
    <label for="enabled">Activer :
        <input id="enabled" name="enabled" type="checkbox">
    </label>
    <br>
    <input class="btn btn-primary" name="article_submit" type="submit" value="Add">
</form>