<form id="article_form" method="post">
    <label for="title">Titre :</label>
        <input id="title" name="title" type="text" required="required">
    <br>
    <label for="content">Contenu :</label>
        <textarea id="content" name="content" required="required"></textarea>
    <br>
    <label for="enabled">Activer :</label>
        <input id="enabled" name="enabled" type="checkbox">
    <br>
    <input name="article_submit" type="submit" value="Envoyer &rarr;">
</form>