<form id="article_form" method="post">
    <label for="name">Nom* :</label>
        <input id="name" name="name" type="text" required="required">
        <?php
        if (isset($name_error)) {
            echo '<div class="error">'.$name_error.'</div>';
        }
        ?>
    <br>
    <label for="email">Email* :</label>
        <input id="email" name="email" type="email" required="required">
        <?php
        if (isset($email_error)) {
            echo '<div class="error">'.$email_error.'</div>';
        }
        ?>
    <br>
    <label for="message">Message* :</label>
        <textarea id="message" name="message" required="required"></textarea>
        <?php
        if (isset($message_error)) {
            echo '<div class="error">'.$message_error.'</div>';
        }
        ?>
    <br>
    <input name="article_submit" type="submit" value="IWantToContactU &rarr;">
</form>