<div class="masthead">
    <ul class="nav nav-pills pull-right">
        <?php
        //TODO SI on est connecté, on affiche
        ?>
        <li class="active"><a href="<?=WEBDIR?>admin/index.php">Administration</a></li>
        <li><a href="<?=WEBDIR?>logout.php">Logout</a></li>
        <?php
        //TODO SINON
        ?>
        <li><a href="<?=WEBDIR?>login.php">Login</a></li>
        <?php
        //TODO fin
        ?>
    </ul>
    <h3 class="muted clearfix">My First Blog</h3>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <ul class="nav">
                    <li><a href="<?=WEBDIR?>index.php">Accueil</a></li>
                    <li><a href="<?=WEBDIR?>articles.php">Articles</a></li>
                    <li><a href="<?=WEBDIR?>contact.php">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">